language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install python-coveralls

script:
    - coverage run --source='.' --branch writeMusic.py

after_success:
    - coveralls
