language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script: python writeMusic.py
    coverage run --branch writeMusic.py

after_success:
  coveralls
